# Generated by Django 3.1.1 on 2022-04-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
