# Generated by Django 3.1.1 on 2022-04-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_django', '0002_auto_20220412_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_user',
        ),
    ]
